mathsMarks = float(input("Enter your maths marks : "))
socialMarks = float(input("Enter your social marks : "))
scienceMarks = float(input("Enter your science marks : "))
englishMarks = float(input("Enter your english marks : "))
kannadaMarks = float(input("Enter your kannada marks : "))
sanskritMarks = float(input("Enter your sanskrit marks : "))

#calculating percentage
avg =  (mathsMarks+socialMarks+scienceMarks+englishMarks+kannadaMarks+sanskritMarks)/6
print("Average = ", avg)
